### ISSUE TITLE
Export mapping: support automatic grouping if hidden elements

### ISSUE THREAD

**Issue by manuelma** [Spine-project/Spine-Database-API#117]
Usually one wants to see each 'vertical header' exactly once when there're 'hidden mappings'. But that means we also need to define how to group all the values for that header in the body of the table. E.g.:

From this (might happen if a mapping has Position.hidden):

| . | obj1 |
| --- | --- |
| . | param1 |
| index1 | x |
| index1 | y |
| index2 | z |
| index2 | w |

To this:

| . | obj1 |
| --- | --- |
| . | param1 |
| index1 | group_fn(x, y) |
| index2 | group_fn(z, w) |

**Comment by soininen** [comment]
This is great addition! I hope no one will start requesting more complicated aggregation functions... or maybe that's where this will go?

**Comment by manuelma** [comment]
I expect max, min, and mean to be eventually requested. Should be easy to add the machinery but we need to know where to stop, definitely!
