### ISSUE TITLE
Export mapping: filter by parameter type

### ISSUE THREAD

**Issue by manuelma** [Spine-project/Spine-Database-API#118]
In the old export to excel, for the same class, we send timeseries data to one sheet, map data to another sheet, and 'scalar' data to yet another sheet. Moreover, for map data we also use a different sheet for each number of dimensions.

It can even happen that the same parameter has different value types for different entity/alternative, so the only way to achieve what we want here, is to effectively have a way to determine which parameter value type a mapping will output.

**Comment by soininen** [comment]
This would be an additional filter to the ones mentioned in Spine-project/Spine-Toolbox#1260.

**Comment by jkiviluo** [comment]
@manuelma Was this closed on purpose? There is ongoing discussion in https://github.com/Spine-project/Spine-Toolbox/issues/1260, but this would be a targeted issue for this

**Comment by jkiviluo** [comment]
And I just continued to discuss in the 'wrong' thread. But we can move here if we want.

**Comment by manuelma** [comment]
ParameterValueTypeMapping is already implemented in spinedb_api, that's why I close this.

**Comment by manuelma** [comment]
Basically, it yields a string, either "single_value, time_series, time_pattern, array, or xd_map", where x is the map dimensionality. If you want to do changes, go ahead, tests will fail if the excel export from Spine DB Editor gets broken.
