### ISSUE TITLE
Speed up export mapping

### ISSUE THREAD

**Issue by manuelma** [Spine-project/Spine-Database-API#124]
I have migrated the old hard-coded excel export mapping to using the new API. The code's much cleaner, but then again performance is also much (much) worse. I think we query the db too much, queries aren't free and we might want to cache more. I'll give it a try now.

**Comment by manuelma** [comment]
Actually I partly lied. The problem is not the queries, although that can be sped up a little bit.

The main culprit for poor performance was `write()`, and the fact that we need to call it once per mapping. `write()` calls `_new_write()` which loads and saves the workbook many times. I will change it so `write()` accepts a variable number of mappings so we can call it once with all the mappings...

**Comment by soininen** [comment]
>The main culprit for poor performance was write(), and the fact that we need to call it once per mapping.

I suspected the queries might become a bottleneck when I initially implemented the mappings. Interesting to see that the main bottleneck may actually be somewhere else. Good to have such a performance 'benchmark' and nice that you're working on improving it @manuelma!

**Comment by manuelma** [comment]
I'm happy for now.
