### ISSUE TITLE
Make exporter as fast as possible

### ISSUE THREAD

**Issue by manuelma** [Spine-project/Spine-Database-API#128]
At the moment exporter *feels* slow. We should try and optimize it without touching the API design, which is really nice to work with.

I believe one reason for the slowness is that each mapping queries the db independently. But I think we could start with a very general query in the root, and pass it to the children recursively so each child adds one or more conditions, and then we'd have a single query that we can run to retrieve everything we want. 

I might give this a try soon.

**Comment by manuelma** [comment]
Something merged into master. I hope I didn't break much, it's a pretty big change. I just made sure all tests pass and all *my* exporters work as expected.

It's between 3 and 4 times faster now according to my measurements. Not a huge deal, but worth it.

Now it works like this: The root mapping creates an empty query and passes it to all mappings in the hierarchy (including itself). Each mapping adds some columns and some filters as it fits. Then the query is run, and again, each row in the result is passed (recursively this time) to all mappings in the hierarchy to incrementally build the output rows.

So it's exactly the same concept, or very similar. The previous implementation was, in fact, like a Python implementation of SQL's SELECT statement.

The biggest advantage of the new approach, is that we have only one query, so we can use the `yield_per()` method which is basically like magic. `yield_per()` basically divides the query into multiple chunks so only one needs to be in memory at a time. This is what is dividing the time by 3 or 4.

**Comment by jkiviluo** [comment]
I've been exporting stuff and haven't seen any problems. However, it's been only CSV. Feels faster, but it's rather small data sets.

**Comment by manuelma** [comment]
I'm not sure how to make this faster at the moment so let's close and see what happens.
