### ISSUE TITLE
Lift the type property from JSON parameter value into own column

### ISSUE THREAD

**Issue by manuelma** [Spine-project/Spine-Database-API#129]
This came up in Virtual 2021. It seems that we align, but we can discuss details here.

I will start trying to implement this to identify any key decisions.

cc @soininen

**Comment by manuelma** [comment]
I forgot: this will be coupled with some sort of `valid types` column in the `parameter_definition` table to do validation. We need to figure out the best way to implement this (DB level vs app level validation).

**Comment by soininen** [comment]
I think it is OK to keep the `type` field in JSON for now.

**Comment by manuelma** [comment]
Thanks @soininen 

If it's easy to remove the type from the 'top level' and just keep it in the Map internal nodes, that would the best for me so I will try.

Another issue is parameter value lists. I feel that we don't need complex parameter values there. My inclination is to only accept plain values in the list (string, number, bool, and null). In that case we don't need to introduce the type to that table. @jkiviluo @DillonJ what do you think?

**Comment by jkiviluo** [comment]
Would it be problem to rename the `type` to something that says that it will be further defining the qualities of the type. I'm bit afraid of later confusion.

I don't see a use case for complex parameter values in the parameter value lists. I suppose we would have parameter type `list` or something like that? Or is it enough that we have the separate tables?

**Comment by manuelma** [comment]
Thanks @jkiviluo my comments below

> Would it be problem to rename the type in the JSON to something that says that it will be further defining the qualities of the type column
I don't think we need that, there's no further definition needed. Maybe it's better to just remove the type from the top-level of the json and keep it only in the map internal leaves. We still need to define the binary format for the value field though (the next step) which means we shouldn't care too much about the json.

> I don't see a use case for complex parameter values in the parameter value lists
Ok cool. I think it's ok to only accept simple values. Not even duration or datetime.

> I suppose we would have parameter type list or something like that? Or is it enough that we have the separate tables?

No, we don't need it. The json format doesn't have the "list" type.

**Comment by jkiviluo** [comment]
> Maybe it's better to just remove the type from the top-level of the json and keep it only in the map internal leaves.

Right. @soininen and me had some chat and thought that this would be fine for now. If we want to have binary arrays later we can have another data type for that (and map's can remain as a very flexible data structure).

> Not even duration or datetime.

No need for these either IMHO.

**Comment by manuelma** [comment]
> If we want to have binary arrays later we can have another data type for that

My idea is not to introduce any new types, but rather reengineer the current JSON format into a fast and efficient binary format that applies to all types (notably time_series, map, and array)

**Comment by jkiviluo** [comment]
If that works, it would be great. I just feel that if you have an array of e.g. 20x8760, it would be better to provide the structure and datetime keys (start time and step duration) as pre-information instead of inside the leaves. That would make it possible to read directly from the right place in the binary data when you browse the data.

**Comment by manuelma** [comment]
> it would be better to provide the structure and datetime keys (start time and step duration) as pre-information instead of inside the leaves

So far by leaves I mean exclusively *map* leaves, not time-series or array leaves as you seem to be referring to? Of course what you say is what we should be aiming for. My impression is typically one would reserve some bytes at the beginning to provide that sort of 'metadata'. I believe this is what most binary formats do.

**Comment by soininen** [comment]
@manuelma is there more work planned for this?

**Comment by manuelma** [comment]
I think we're done.
