### ISSUE TITLE
Checking version in DB socket server communication

### ISSUE THREAD

**Issue by manuelma** [Spine-project/Spine-Database-API#131]
At the moment there's no way of ensuring from toolbox that the user has the right SpineInterface. In the past, when SpineInterface depended on spinedb_api (through PyCall), SpineInterface was able to check for itself, that spinedb_api was the right version.

But now the communication is done through the spine db socket server. This means that if we change the server API, and the user updates spinedb_api but not SpineInterface, there will be problems difficult to communicate to the user. The user will probably just see a low-level method error or decoding error, because their SpineInterface doesn't know how to talk to the new spinedb_api socket server.

I believe the solution here is to check versions in the socket communication. That is, we need to send something like a version with every message to the server, so the server can check and respond appropriately. If the version is not what the server expects, it can respond with a known error that the client can catch and convert into a message: "Please update SpineInterface by doing this and that"

Cc @PekkaSavolainen

**Comment by jkiviluo** [comment]
Sounds like a good idea. I assume that the bits involved is minimal and won't noticeably affect performance.

**Comment by manuelma** [comment]
I think so @jkiviluo 

I guess we need to reserve some reasonable amount of bytes for the version, but not too many. I can't see ourselves having hundreds of different server versions. We should aim for stability and use the version only under some real difficult circumstances.

Also, the client doesn't exchange much with the server. It's typically once to get all the data needed, and then once again to write data back. So it really shouldn't be too much of a problem. Some other socket-server based frameworks such as Jupyter use much more metadata than that, and exchange much more often.

**Comment by soininen** [comment]
Is it possible to query the server's version just once when the socket is connected?

**Comment by manuelma** [comment]
This is done in latest master, and used by latest SpineInterface and SpineOpt.

I ended up implementing a mildly insane system where both client and server check each other's version, and refuse to proceed if they're not happy. With this we can force upgrades from both ends, so we can comfortably change the api from one side and let the other side know. I hope it works well. Will close now.
