### ISSUE TITLE
Apply parameter value math directly in the query?

### ISSUE THREAD

**Issue by manuelma** [Spine-project/Spine-Database-API#132]
Re https://github.com/Spine-project/Spine-Toolbox/issues/1395

At the moment, parameter value math is achieved by prepending a serialized JSON to the value that comes out of the query. The JSON is basically a dictionary that encodes the operations to be performed. `from_database` then splits that JSON and applies the math in pure Python.

An alternative is to move the math a little ahead in time, so the value that comes out of the query is already transformed. (This can be achieved by doing the math in Python, inserting the converted value into a temp table, and then joining that table in the modified `parameter_value` query.)

For some reason I don't feel too good about prepending and splitting (the current approach). The alternative seems cleaner to me, but I'm not sure why.

**Comment by soininen** [comment]
This has now been implemented.
