### ISSUE TITLE
Parameter not found trying to import a Map value

### ISSUE THREAD

**Issue by jimhommes** [Spine-project/Spine-Database-API#133]
I'm using spinedb_api to import multiple values through Python. I've been struggling for some hours now trying to fix the following problem.

I'm getting the following output using import_object_parameter_values:
```
WARNING:root:Could not import parameter value for 'Cofiring', class 'Overnight Cost (OC)', parameter 'Overnight Cost (OC)': Parameter not found.
```

The message makes sense: the structure is that every object has one parameter with a Map value called the same as the object class. This is the case, and I have verified that. 

This is curious as I'm taking the parameter name from the export from SpineDB. So I'm at a loss: the value is in SpineDB but the error message states that the Parameter is not found. 

This is the code:
```
db_emlab.import_object_parameter_values([('Overnight Cost (OC)', tech, param_name, valuemap_per_fuel.values)])
```

where tech is the object name, param_name is the parameter name from the SpineDB and valuemap_per_fuel is the SpineDB Map object. I have tried using to_dict() and other methods here. 

What could be going wrong? Any help would be appreciated!

**Comment by manuelma** [comment]
How do I test this? Can you provide steps from a clean python session into the error?

It is not clear to me what are the contents of the db at the moment of running that line of code. Is a parameter called `Overnight Cost (OC)` defined for class `Overnight Cost (OC)`?

**Comment by jimhommes** [comment]
I'm sorry, I was in a bit of a hurry when I wrote the message. I've taken some time to create a test Spine project describing my problem.
[parameter_name.zip](https://github.com/Spine-project/Spine-Database-API/files/6638697/parameter_name.zip)

It's now not giving me the warning of 'parameter not found', so let me alter my question: how can I efficiently re-import a value initially loaded as a `Map` value? In the example project I load the map value, change an entry and would like to import it back. I can't find as what structure or object I should provide it to the function.

**Comment by manuelma** [comment]
Thanks @jimhommes 

I haven't tried the project, but a `Map` should do. For instance, if `valuemap_per_fuel` is an instance of `Map`, the below should work:

`db_emlab.import_object_parameter_values([('Overnight Cost (OC)', tech, param_name, valuemap_per_fuel)])`

**Comment by jimhommes** [comment]
I just smacked my forehead. I was trying to import into the wrong database. After your edit the test project I sent works, and the main project will be fixed after the edit.

The error `parameter not found` made me assume the `object_class` and `object` was found, but apparently none of these were available as it was the wrong database entirely.

Sorry about that, thanks for your help!
