### ISSUE TITLE
Querying select amounts of data

### ISSUE THREAD

**Issue by jimhommes** [Spine-project/Spine-Database-API#134]
At the moment, anytime I need something from SpineDB in my Python script I export the entire database using the API's export functions. This is very intensive especially since sometimes I only need one value.

Is it possible to constrain these queries? E.g., I would like to only query the object parameter values which belong to one object class. Is this possible through the list of IDs which is a parameter to the export functions? If so, how do I get the IDs?

Thanks in advance for any help!

**Comment by soininen** [comment]
The API provided by the `export_functions` module in spinedb_api is not really intended for querying specific database items but to actually blurt out the entire database to be later imported by `import_functions`. For more specific queries you use the APIs provided by DatabaseMapping (write-only) and DiffDatabaseMapping (read-write). These allow you to do actual SQL queries. For example, to query parameter values of specific object class:

```python
db_map = DatabaseMapping(url)
subquery = db_map.object_parameter_value_sq
for value_row in db_map.query(subquery).filter(subquery.c.object_name == "my_object"):
    print(from_database(value_row.value, value_row.type)
```

Check out the properties ending with `_sq` in `DatabaseMappingBase` class in `db_mapping_base.py`. Unfortunately we don't have much documentation yes besides the sometimes cryptic docstrings in the source files.

**Comment by jimhommes** [comment]
I had seen the SQL queries in `DiffDatabaseMapping` and `DatabaseMapping` but because I also found the `export_functions` I assumed they were being used for a bit lower-level function that I couldn't find. 

Your example is very helpful and I'll get to work with it. Thanks for your help, next time I'll post in the discussions thread.
