### ISSUE TITLE
Doc build errors

### ISSUE THREAD

**Issue by ererkka** [Spine-project/Spine-Database-API#136]
Building the docs using `make html`, generates the following errors:

```
WARNING: autodoc: failed to import module 'database_mapping' from module 'spinedb_api'; the following exception was raised:
No module named 'spinedb_api.database_mapping'
WARNING: autodoc: failed to import module 'database_mapping_base' from module 'spinedb_api'; the following exception was raised:
No module named 'spinedb_api.database_mapping_base'
WARNING: autodoc: failed to import module 'database_mapping_check_mixin' from module 'spinedb_api'; the following exception was raised:
No module named 'spinedb_api.database_mapping_check_mixin'
WARNING: autodoc: failed to import module 'database_mapping_query_mixin' from module 'spinedb_api'; the following exception was raised:
No module named 'spinedb_api.database_mapping_query_mixin'
WARNING: autodoc: failed to import module 'diff_database_mapping' from module 'spinedb_api'; the following exception was raised:
No module named 'spinedb_api.diff_database_mapping'
WARNING: autodoc: failed to import module 'diff_database_mapping_add_mixin' from module 'spinedb_api'; the following exception was raised:
No module named 'spinedb_api.diff_database_mapping_add_mixin'
WARNING: autodoc: failed to import module 'diff_database_mapping_base' from module 'spinedb_api'; the following exception was raised:
No module named 'spinedb_api.diff_database_mapping_base'
WARNING: autodoc: failed to import module 'diff_database_mapping_commit_mixin' from module 'spinedb_api'; the following exception was raised:
No module named 'spinedb_api.diff_database_mapping_commit_mixin'
WARNING: autodoc: failed to import module 'diff_database_mapping_remove_mixin' from module 'spinedb_api'; the following exception was raised:
No module named 'spinedb_api.diff_database_mapping_remove_mixin'
WARNING: autodoc: failed to import module 'diff_database_mapping_update_mixin' from module 'spinedb_api'; the following exception was raised:
No module named 'spinedb_api.diff_database_mapping_update_mixin'
WARNING: autodoc: failed to import module 'json_mapping' from module 'spinedb_api'; the following exception was raised:
No module named 'spinedb_api.json_mapping'
```

Many of the modules seem to be renamed, but the changes are not reflected in the file *docs/sources/autogen_apidocs/spinedb_api.rst*. How to update that easily?

**Comment by soininen** [comment]
Shouldn't we just copy the machinery we use to build the documentation from `spinetoolbox`?

**Comment by PekkaSavolainen** [comment]
How about?

1. Remove *docs/sources/autogen_apidocs* directory
2. In docs/ dir do `sphinx-apidoc -o source/autogen_apidocs ../spinedb_api`
3. make html

**Comment by PekkaSavolainen** [comment]
> Shouldn't we just copy the machinery we use to build the documentation from spinetoolbox?

Yes definitely. To make this consistent with Toolbox, the *source/autogen_apidocs/* directory should be ignored by Git. In addition. there's something else that needs to be updated (maybe in conf.py), because 'make html' fails if there's no *source/autogen_apidocs/modules.rst* file.

**Comment by soininen** [comment]
I can work on bringing at least the documentation build system on par with Toolbox. I'll do the same for the Engine repository as well. I think it would be nice if we got this kind of polishing ready before the EU project finishes.

**Comment by soininen** [comment]
It is now possible to generate the documentation including the API docs by running `bin/build-doc` (Windows) or `bin/build-doc.py` (*NIX) just like in Toolbox. This works also in the Engine repository.

**Comment by ererkka** [comment]
Thanks Antti, excellent solution.
