### ISSUE TITLE
Commit comments don't end up in the database

### ISSUE THREAD

**Issue by soininen** [Spine-project/Spine-Database-API#137]
Looks like the `comment` parameter of `DiffDatabaseMappingCommitMixin.commit_session()` is unused and the commit's comment doesn't get stored anywhere.

**Comment by manuelma** [comment]
Nice catch! It looks like we forgot to use the argument in `diff_db_mapping_commit_mixin.py:40`

**Comment by soininen** [comment]
Fixed.
