### ISSUE TITLE
Deleting objects from MySQL database fails

### ISSUE THREAD

**Issue by soininen** [Spine-project/Spine-Database-API#154]
Deleting in itself doesn't fail but when I try to commit the changes I get the following error:

DBAPIError while commiting changes: (1451, 'Cannot delete or update a parent row: a foreign key constraint fails (`soininen`.`object`, CONSTRAINT `fk_object_entity_id_entity` FOREIGN KEY (`entity_id`, `type_id`) REFERENCES `entity` (`id`, `type_id`))')

**Comment by soininen** [comment]
Looks like missing ON UPDATE and ON DELETE clauses were indeed the culprit here. Hopefully the above commit fixes the issue.

**Comment by ererkka** [comment]
After the fix, creating a new Spine DB gives the following error:

```
Unable to create new Spine db at 'mysql+pymysql://...': Unable to create Spine database: (pymysql.err.OperationalError) (3823, "Column 'type_id' cannot be used in a check constraint 'ck_object_type_id': needed in a foreign key constraint 'fk_object_entity_id_entity' referential action.")
[SQL: 
CREATE TABLE object (
	entity_id INTEGER NOT NULL, 
	type_id INTEGER NOT NULL, 
	CONSTRAINT pk_object PRIMARY KEY (entity_id), 
	CONSTRAINT fk_object_entity_id_entity FOREIGN KEY(entity_id, type_id) REFERENCES entity (id, type_id) ON DELETE CASCADE ON UPDATE CASCADE, 
	CONSTRAINT ck_object_type_id CHECK (`type_id` = 1)
)

]
(Background on this error at: http://sqlalche.me/e/13/e3q8).
```

**Comment by soininen** [comment]
> Or then remove the ON UPDATE action, maybe those id’s will never be changed anyway.

I don't think that caluse makes a sense here. Lets just drop it.

**Comment by ererkka** [comment]
Upgrading an earlier results in an empty DB editor: 

```
    raise errorclass(errno, errval)
sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (3823, "Column 'type_id' cannot be used in a check constraint 'ck_object_type_id': needed in a foreign key constraint 'fk_object_entity_id_entity' referential action.")
[SQL: ALTER TABLE object ADD CONSTRAINT fk_object_entity_id_entity FOREIGN KEY(entity_id, type_id) REFERENCES entity (id, type_id) ON DELETE CASCADE ON UPDATE CASCADE]
(Background on this error at: http://sqlalche.me/e/13/e3q8)
```

**Comment by soininen** [comment]
> Upgrading an earlier db results in an empty DB Editor. An error is in the console:

If I got this right, Alembic upgrade scripts fail on this particular MySQL database because one of the upgrades (revision `738d494a08ac`) applies the ON UPDATE clause on 'object' and 'relationship' tables which in turn causes that error. I tested the updages on another MySQL database where they worked fine.

I'm unsure what can be done here as revision `738d494a08ac` cannot be reliably applied to some MySQL databases. Is there a way to skip the revision somehow?

**Comment by manuelma** [comment]
Good job here!

> I'm unsure what can be done here as revision 738d494a08ac cannot be reliably applied to some MySQL databases.

I wonder why not. Normally, all dbs should have gone throught the same migration path. Can we share the one that didn't? I think we need to try and identify what went wrong.

> Is there a way to skip the revision somehow?

Should be possible by messing with alembic internals, but feels like something I definitely would like to avoid.

**Comment by soininen** [comment]
>  Can we share the one that didn't? I think we need to try and identify what went wrong.

Unfortunately, that particular database server isn't really accessible from outside the TraderRES project.

On a bright side, we were able to sidestep the upgrade issue by recreating the database using the latest revision.

I suspect there aren't (m)any MySQL databases left that would need an upgrade and are thusly susceptible to upgrade failure.

**Comment by manuelma** [comment]
Thank you! Should we close this then?
