### ISSUE TITLE
Error `KeyError: key :query not found` when calling db outside spine toolbox

### ISSUE THREAD

**Issue by mihlema** [Spine-project/Spine-Database-API#163]
When I execute my `spineopt` tool calling a spine-db in spine-toolbox, everything seems to work. However, when I do the exact thing outside of spine-toolbox (in my case Atom), I get the following error:
`ERROR: LoadError: KeyError: key :query not found`
I assume that `:query` is only available when called through toolbox? I wouldn't mind executing through toolbox, but for developing/debugging SpineOpt it is somewhat cumbersome.

**Comment by DillonJ** [comment]
Do you need to update SpineInterface?

**Comment by mihlema** [comment]
Sorry for the noise here. After all, the problem originated from my Julia side PyCall. It seems like it was looking at the wrong conda environment, I don't really know why now. Anyways, it works flawlessly again. Kudos to @manuelma for the instant help.
