### ISSUE TITLE
"from_list" parameter value type

### ISSUE THREAD

**Issue by manuelma** [Spine-project/Spine-Database-API#165]
At the moment, when we update a value in a `parameter_value_list`, the `parameter_value` table is not automatically updated. This is because the `value` field in the `parameter_value` table is not linked to the list at all (rather, the value is just repeated). I think we should link it via a new parameter value `type` named `"from_list"` or something.

**Comment by DillonJ** [comment]
Can we also have a "static_value" type that allows us to specify a list_value as a parameter value that is independent of the list if you know what I mean?

**Comment by DillonJ** [comment]
I added a comment to https://github.com/Spine-project/Spine-Database-API/issues/151 on how we could easily add the "static_value" symbol-like value

Feels like a small change that adds a lot of functionality.

**Comment by manuelma** [comment]
I think the 'free value' table can be useful to define values that can be referenced both from `parameter_value` and the new `list_value` table (implemented in the context of #151). But maybe we can create another issue for that as I think it's different functionality. This issue is more about improving/fixing something particular about parameter value lists.

**Comment by manuelma** [comment]
Done.
