### ISSUE TITLE
Can't send bytes over the server

### ISSUE THREAD

**Issue by manuelma** [Spine-project/Spine-Database-API#173]
The DB server uses JSON to serialize/deserialize data, but JSON doesn't handle all possible data types in our db such as bytes, which means that adding or updating any parameter value is impossible via the server.

**Comment by soininen** [comment]
Does the client need to send the value to the server as the final binary blob? I'm just curious on the details since I'm not familiar with the DB server at all.

**Comment by manuelma** [comment]
You're right, that's not a necessity per se but the idea is that the client has access to the low level api so we don't need to do much interpretation. I would like the client to be able to send the bytes as it means we don't need to do anything on the server side.

For example, if the client wants to add parameter values, they could send `["call_method", "add_parameter_values", ({"object_id": 1, "parameter_definition_id": 2, "alternative_id": 3, "type": None, "value": b"something"})]` (serialized as JSON), but that would fail because the serialization would convert b"something" into just "something".

**Comment by manuelma** [comment]
But I think the most elegant solution would be to keep the values as bytes for as long as possible. For example now, we read the bytes values from the db, convert them to string within a JSON document, and then back into bytes to send them through the socket. That defeats a big part of the purpose of storing values as BLOB.

**Comment by manuelma** [comment]
Fixed. Now we send bytes in a tail that goes directly into the socket without any JSON loading/dumping in between. Should help for whenever we adopt a real binary format for our parameter values (not our current JSON).
